version: 2
multi-ecosystem-groups:
  dependency:
    schedule:
      interval: "weekly"
      target-branch: dev
      labels: [ ]

updates:
  - package-ecosystem: github-actions
    multi-ecosystem-group: "dependency"
    directory: /
    patterns:
      - "*"

  - package-ecosystem: npm
    multi-ecosystem-group: "dependency"
    directory: /
    patterns:
      - "*"

  - package-ecosystem: gradle
    multi-ecosystem-group: "dependency"
    directory: /
    patterns:
      - "*"
