project_id_env: "CROWDIN_PROJECT_ID"
api_token_env: "CROWDIN_PERSONAL_TOKEN"

preserve_hierarchy: false
files:
    - source: patches/src/main/resources/addresources/values/strings.xml
      translation: patches/src/main/resources/addresources/values-%android_code%/strings.xml
      skip_untranslated_strings: true
