package app.revanced.patches.instagram.story.locationsticker

import app.revanced.patcher.gettingFirstMethodDeclaratively
import app.revanced.patcher.patch.BytecodePatchContext

internal val BytecodePatchContext.locationStickerRedesignGateMethod by gettingFirstMethodDeclaratively("map_location_sticker_fragment")
